export const unitStatuses = [
  {
    status: 'All',
    count: 2,
    className: 'border-gray-200 bg-gray-50  text-gray-700',
  },
  {
    status: 'Occupied',
    count: 2,
    className: 'border-blue-200 bg-blue-50 text-blue-700',
  },
  {
    status: 'Vacant',
    count: 2,
    className: 'border-[#FEDF89] bg-[#FFFAEB] text-[#B54708]',
  },
  {
    status: 'Guranteed',
    count: 2,
    className: 'border-[#ABEFC6] bg-[#ECFDF3] text-[#067647]',
  },
  {
    status: 'Applied',
    count: 2,
    className: 'border-blue-200 bg-blue-50 text-blue-700',
  },
  {
    status: 'In Progress',
    count: 2,
    className: 'border-purple-200 bg-purple-50 text-purple-700',
  },
];

export const unitModelData = [
  'Unit Model A',
  'Unit Model B',
  'Unit Model C',
  'Unit Model D',
  'Unit Model E',
];
export const stepSignupData = [
  {
    label: 'Your details',
    desc: 'Please provide your name and email',
  },
  {
    label: 'Verify your email',
    desc: 'Choose a secure password',
  },
  {
    label: 'About your portfolio',
    desc: 'Start collaborating with your team',
  },
  {
    label: 'Add your first property',
    desc: 'Share posts to your social accounts',
  },
];

export const statesList = [
  'AL',
  'AK',
  'AZ',
  'AR',
  'CA',
  'CO',
  'CT',
  'DE',
  'FL',
  'GA',
  'HI',
  'ID',
  'IL',
  'IN',
  'IA',
  'KS',
  'KY',
  'LA',
  'ME',
  'MD',
  'MA',
  'MI',
  'MN',
  'MS',
  'MO',
  'MT',
  'NE',
  'NV',
  'NH',
  'NJ',
  'NM',
  'NY',
  'NC',
  'ND',
  'OH',
  'OK',
  'OR',
  'PA',
  'RI',
  'SC',
  'SD',
  'TN',
  'TX',
  'UT',
  'VT',
  'VA',
  'WA',
  'WV',
  'WI',
  'WY',
  'DC',
  'AS',
  'GU',
  'MP',
  'PR',
  'UM',
  'VI',
];

export const TenantGuaranteeFeatures = [
  '12 months rent guaranteed (up to $100,000)',
  'Full eviction management',
  'Releasing assistance',
  'Rent reporting to the credit bureaus',
  'Security deposit waiver (for an additional 1% of monthly rent/month)',
];
