import {
  AiIcon,
  AviIcon,
  CsvIcon,
  DocIcon,
  DocxIcon,
  FlgIcon,
  GifIcon,
  HtmlIcon,
  ImgIcon,
  JpegIcon,
  JpgIcon,
  Mp3Icon,
  Mp4Icon,
  MpegIcon,
  PdfIcon,
  PngIcon,
  PptIcon,
  PptxIcon,
  PsdIcon,
  RarIcon,
  TiffIcon,
  TxtIcon,
  WavIcon,
  WebpIcon,
  XlsIcon,
  XlsxIcon,
  ZipIcon,
} from '@assets/iconComponents';

export const iconsByExtension = {
  rar: <RarIcon />,
  zip: <ZipIcon />,
  pdf: <PdfIcon />,
  jpg: <JpgIcon />,
  png: <PngIcon />,
  img: <ImgIcon />,
  jpeg: <JpegIcon />,
  gif: <GifIcon />,
  tiff: <TiffIcon />,
  webp: <WebpIcon />,
  csv: <CsvIcon />,
  txt: <TxtIcon />,
  xls: <XlsIcon />,
  ppt: <PptIcon />,
  pptx: <PptxIcon />,
  xlsx: <XlsxIcon />,
  ai: <AiIcon />,
  flg: <FlgIcon />,
  psd: <PsdIcon />,
  mp3: <Mp3Icon />,
  mp4: <Mp4Icon />,
  wav: <WavIcon />,
  avi: <AviIcon />,
  html: <HtmlIcon />,
  mpeg: <MpegIcon />,
  doc: <DocIcon />,
  docx: <DocxIcon />,
};
