export const SINGLE_UNIT_VALUE = {
  name: '',
  phone: '',
  email: '',
  address1: '',
  address2: '',
  city: '',
  state: '',
  zip: '',
  description: '',
  bedrooms: '',
  bathrooms: '',
  amenities: [''],
  sqfeet: '',
  rent: '',
  parking: false,
  images: [],
};
