import { Work_Sans } from "next/font/google";
import localFont from "next/font/local";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const nasalization = localFont({
  src: "../nasalization-rg.otf",
  variable: "--font-nasalization",
  display: 'swap',
});
const montserrat = localFont({
  src: "../Montserrat-Regular.ttf",
  variable: "--font-montserrat",
});
const helvetica = localFont({
  src: "../Helvetica.ttf",
  variable: "--font-helvetica",
});
const helvetica_neue = localFont({
  src: "../Helvetica Neue.otf",
  variable: "--font-helvetica_neue",
});
const workSans = Work_Sans({
  subsets: ["latin"],
  variable: '--font-worksans',
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${nasalization.variable} ${montserrat.variable} ${helvetica.variable} ${helvetica_neue.variable} ${workSans.variable}`}
      >{children}</body>
    </html>
  )
}